### ISSUE TITLE
hieroglyph-quickstart crashes (no attribute QUICKSTART_CONF)

### ISSUE THREAD

**Issue by etingof** [nyergler/hieroglyph#120]
$ hieroglyph-quickstart 
Traceback (most recent call last):
  File "/Users/me/slides/venv/bin/hieroglyph-quickstart", line 7, in <module>
    from hieroglyph.quickstart import quickstart
  File "/Users/me/slides/venv/lib/python3.4/site-packages/hieroglyph/quickstart.py", line 29, in <module>
    sphinx.quickstart.QUICKSTART_CONF += u"""
AttributeError: 'module' object has no attribute 'QUICKSTART_CONF'

$ pip list 
alabaster (0.7.9)
Babel (2.3.4)
docutils (0.13.1)
hieroglyph (0.7.1)
imagesize (0.7.1)
Jinja2 (2.9.4)
MarkupSafe (0.23)
pip (1.5.6)
Pygments (2.2.0)
pytz (2016.10)
requests (2.13.0)
setuptools (2.1)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.5.2)

Downgrading towards Sphinx 1.4.1 (and possibly other versions prior to 1.5.2) fixes this issue for me.

**Comment by nyergler** [comment]
Looks like Sphinx 1.5 changed the way the configuration is assembled during quickstart. It's better overall, but is going to require some changes to Hieroglyph to make it work.

**Comment by scanf** [comment]
Also seeing this, but easily avoided by running `pip install sphinx==1.4.1`.

**Comment by ghisvail** [comment]
This bug is quite a biggy as I don't see pinning down the version of `Sphinx` as a long-term solution.

**Comment by nyergler** [comment]
I agree that pinning isn't a long-term solution, @ghisvail. I don't have the bandwidth to work on this at the moment, but I'd be happy to review and merge a PR.

**Comment by bilderbuchi** [comment]
question is, can you go down to sphinx 1.4 just for the quickstart, then use regular sphinx 1.5 for the rest of the writing?

**Comment by petarmaric** [comment]
Yes you can, that's my current workaround. Although you might want to update your conf.py afterwards.

**Comment by nyergler** [comment]
@bilderbuchi Prior to Sphinx 1.5 the quickstart configuration was stored in a string variable and formatted with configuration values. In that case Hieroglyph just imported it and then concatenated additional configuration onto it. In Sphinx 1.5 [quickstart.py](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/quickstart.py) has been updated so that it uses a `generate` function to create the empty project from a template directory. I _think_ this means that Hieroglyph needs to have its own template directory, and then call `generate` with the appropriate parameters, but that's just sort of gut level idea.

**Comment by bilderbuchi** [comment]
OK, thank you for the info. In the meantime, I temporarily dropped down to sphinx 1.4 to make a quickstart, and only had to do trivial changes to conf.py when going back up, let's see how far I get. :-)

**Comment by mbukatov** [comment]
It's seem that `sphinx-quickstart` is not designed with extending in mind.

This code from `hieroglyph.quickstart` module which works with older Sphinx:

```
sphinx.quickstart.QUICKSTART_CONF += u"""

# -- Hieroglyph Slide Configuration ------------

extensions += [
    'hieroglyph',
]
"""
```

could be replaced with extending `d` dict in `ask_user` to work with new Sphinx:

```
def ask_user(d):
    """Wrap sphinx.quickstart.ask_user, and add additional questions."""

    ... few lines skipped ...

    # set a few defaults that we don't usually care about for Hieroglyph
    d.update({
        'extensions': ['hieroglyph'],
        ... few lines skipped ...
        })

	... few lines skipped ...
```

Which is possible because template file `sphinx/templates/quickstart/conf.py_t` contains list of extensions in this way:

```
# Add any Sphinx extension module names here, as strings. They can be           
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom           
# ones.                                                                         
extensions = [{{ extensions }}]
```

But it's not possible for other additions/tweaks (such as adding list of hieroglyph options into conf.py), because the template doesn't expect this use case.

So maybe you can try proposing few changes in Sphinx to make work on `hieroglyph-quickstart` easier. I have no idea if upstream would welcome this idea, but it's an option to try.

**Comment by nyergler** [comment]
This should be fixed on the `master` branch. I'll make a new release shortly after we finish ironing out the 1.6 issues.
