### ISSUE TITLE
Convert html slides to pdf

### ISSUE THREAD

**Issue by mileo** [nyergler/hieroglyph#122]
Hi,

How can i convert, save, html slides in pdf format? To publish presentation in slideshare?

Thanks in advance.

**Comment by nyergler** [comment]
I prototyped a tool to do this, https://github.com/nyergler/cascajal, about 3 years ago. It worked for me, but hasn't received much love. It uses a temporary Firefox profile and some extension magic that might not work with modern versions of Firefox.

So... maybe? Now that Phantom 2 is out, Cascajal could conceivably be ported to use that instead of Firefox (Phantom 1 lacked webfont support). I doubt I'll have time in the near future to actually make that port.
