### ISSUE TITLE
Support `plot` directive from `matplotlib.sphinxext.only_directives`

### ISSUE THREAD

**Issue by joonro** [nyergler/hieroglyph#83]
Hi,

It seems currently the `plot` directive is not rendered in slides. For example, with `'matplotlib.sphinxext.plot_directive'` is added in the `conf.py`,

```python
.. plot::

   import matplotlib.pyplot as plt
   import numpy as np
   x = np.random.randn(1000)
   plt.hist(x, 20)
   plt.grid()
   plt.title(r'Normal: $\mu=%.2f, \sigma=%.2f$'%(x.mean(), x.std()))
   plt.show()
```

will not be rendered. It would be great if this is supported!

**Comment by nyergler** [comment]
Other Sphinx extensions should work just fine with Hieroglyph. I wonder if
this isn't getting rendered at all, or if it's not visible due to the slide
CSS. Can you take a look at the generated HTML and see if the plot is
actually in there, but not visible?

**Comment by joonro** [comment]
Thanks for the reply.

It seems the plot is not in there. I just tried it, with the following source:

```rst
Plot directive test
-------------------

.. plot::

   import matplotlib.pyplot as plt
   import numpy as np
   x = np.random.randn(1000)
   plt.hist(x, 20)
   plt.grid()
   plt.title(r'Normal: $\mu=%.2f, \sigma=%.2f$'%(x.mean(), x.std()))
   plt.show()
```

In the Sphinx html output, I've got:

```html
<div class="section" id="plot-directive-test">
<h3>Plot directive test<a class="headerlink" href="#plot-directive-test" title="Permalink to this headline">¶</a></h3>
<p>(<a class="reference external" href="../Slides/Regression-1.py">Source code</a>, <a class="reference external" href="../Slides/Regression-1.png">png</a>, <a class="reference external" href="../Slides/Regression-1.hires.png">hires.png</a>, <a class="reference external" href="../Slides/Regression-1.pdf">pdf</a>)</p>
<div class="figure">
<img alt="../_images/Regression-1.png" src="../_images/Regression-1.png" />
</div>
</div>
```

But for the slide output:

```html
<article class="slide level-3" id="plot-directive-test">
<h3>Plot directive test</h3>

</article>
```

**Comment by nyergler** [comment]
Thanks for testing that and providing a test case. One last question: do
you know what version of Hieroglyph you're using?

**Comment by joonro** [comment]
Sure. It seems I'm using 0.6.5:

```posh
> pip search hieroglyph
hieroglyph                - UNKNOWN
  INSTALLED: 0.6.5
  LATEST:    0.6.5.dev
```

I actually tried the latest version (0.7.0?) last night but the results were the same.

**Comment by nyergler** [comment]
I did some digging into 'matplotlib.sphinxext.plot_directive', and the plot is omitted due to the design of that directive. `plot_directive` works by reading the source file, generating the plots, and then injecting new ReStructured Text into the source document with references to the plots. It uses the same template for HTML, LaTeX (PDF), and TeXinfo; the default template is stored in the source file --  https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/sphinxext/plot_directive.py#L345

The issue is that the template depends on the `html` build tag being set to include the plot (https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/sphinxext/plot_directive.py#L348). The Hieroglyph builders set the `slides` build tag, not `html`.

It appears that you can override the template used by setting the `plot_template` in your configuration. I suggest copying the default template as your custom `plot_template` and change:

`..only:: html`

to

`.. only:: html or slides`

See http://sphinx-doc.org/markup/misc.html#directive-only for details on the `only` directive.

**Comment by joonro** [comment]
Thank you so much for the detailed information!

**Comment by lpirl** [comment]
@nyergler, could we extend the default configuration with something like
```python
from matplotlib.sphinxext.plot_directive import TEMPLATE as PLOT_TEMPLATE
plot_template = PLOT_TEMPLATE + """
.. only:: slides

  {% for img in images %}
  .. figure:: {{ build_dir }}/{{ img.basename }}.{{ default_fmt }}
    {% for option in options -%}
    {{ option }}
    {% endfor %}
    {{ caption }}
  {% endfor %}
"""
```
?

**Comment by nyergler** [comment]
@lpirl Yes, setting that in your Sphinx configuration will probably work.

**Comment by lpirl** [comment]
Yes, it does, @nyergler .
What about a more general solution to ship this configuration with hieroglyph?
I really liked that many things worked out of the box (e.g., Graphviz integration) and it would provide a similar experience for the ``plot`` directive.
So, the question rephrased: do you have an idea, where in hieroglyph we could extend Sphinx' default configuration as transparent as possible (of course, the ``include`` must be caught in case it fails etc.).
