### ISSUE TITLE
Bug in 'writer.py' (Since 0.7-dev; not fixed in Rel-0.7)

### ISSUE THREAD

**Issue by AlbertMietus** [nyergler/hieroglyph#93]
The RST file below contain an example of a RST-part that does work to make HTML, but can't be processed with hieroglyph (slides2) after 0.6.5.
Note, the attention line is indented itself and the items below it are even more

(Can't upload the TGZ file, so I have to copy)

--Albert
-------------------------------------------------------------------------------------------------------
=====================================
HITS a BUG in hieroglyph (upto -0.7)
=====================================

Generating HTML will work, but slides (with hieroglyph, and `slides2`) will fail!

Just a HEAD
===========

  .. attention:: Can be anything, which is indented, with a 'list' to follow

     * Python is a programming language that lets you work more quickly and integrate your systems
       more effectively.

     * Python is powerful and fast; plays well with others; runs everywhere; is friendly & easy to
       learn; is Open.

* Python runs on Unix/Linux/BSD, Mac OS X, Windows, iOS, etc. It is ported to (other) virtual machines,
  as Java and .Net

* Python is free to use, even for commercial products, because of its OSI-approved `open source
  license <http://docs.python.org/license.html>`_

NOTES:
======

* The hieroglyph/writer can't handle the piece above. The standaard (sphinx) writer can!
* Removing the indent of `attention` help to make it working.
* It's not about the **Admonition**, it happens at many places that are list like.

  + Or maybe, only when the indention is 'strange'

Result with hieroglyph:
========================

>>> Exception occurred:
>>>  File "/Users/albert/Library/Python_VirtualEnvs/Python3/lib/python3.4/site-packages/hieroglyph/writer.py", line 270, in visit_block_quote
>>>    raise ValueError("The first child of a quote must be a paragraph")
>>> ValueError: The first child of a quote must be a paragraph

**Comment by nyergler** [comment]
The change to `writer.py` in 0.7 was the result of adding support for "quote" slides, which only show a quote with attribution (see https://github.com/nyergler/hieroglyph/pull/76). These are roughly the equivalent of a `blockquote` in HTML. RST uses indentation to denote quoting (http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#block-quotes). With your example, you're actually getting a `blockquote` element emitted when you generate HTML, but browsers ignore it since it contains a subsequent `div`.

I'm uncertain what the best approach here is; just remove the exception that's raised, let it look goofy on the slide? Emit a warning instead of an exception, alerting the user that they have a quote, which may look strange?

**Comment by AlbertMietus** [comment]
Probably raising a error should be avoided. As the rst constitution is legal and (at least) the html builder/writer accept it. 

I see web-slides as a special kind of html. So the html solution is fine. The 'style' it, css should be used. 

Just my humble opinion

Thanks 

--albert
An iPhone is great, but for typing mail

**Comment by nyergler** [comment]
Released 0.7.1, which contains a fix for this. 

Thanks again for reporting.
