### ISSUE TITLE
`slides2` decks open to last slide by default

### ISSUE THREAD

**Issue by jayhesselberth** [nyergler/hieroglyph#95]
I assume this is somehow related to #92, as this is the most recent update to the CSS of the slide deck

Slide decks created under v0.7.1 now open to the *last* slide in the deck, and you have to manually page back to the first slide.

In addition, I can't just add: `#1` to the URL, not sure why that wouldn't work.

One other (minor) thing is that the title slides that weren't explicitly included went away. However, the last slide in the deck is always an acknowledgement client, which AFAIK I don't explicitly ask for either.

**Comment by nyergler** [comment]
Thanks for reporting this; looks like this got introduced with #78: in cases where no specific slide was requested, it was inadvertently triggering the title search.

I suspect the inability to add `#1` to the URL was a side effect of browser URL fragment handling: changing the fragment usually doesn't trigger a reload, since the fragments are never sent to the "server".
